export function buildScopeDoc(answers, sessionId) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });

  const tracks = [
    ["Cataract Patent → Prototype",   "q_track_cataract",  "q_track_cataract_notes"],
    ["Tangential Domain Applications", "q_track_domains",   "q_track_domains_notes"],
    ["EBV / Long COVID Research",      "q_track_ebv",       "q_track_ebv_notes"],
    ["AI Agentic Workflows",           "q_track_ai",        "q_track_ai_notes"],
  ].map(([label, id, nid]) => {
    const priority = answers[id]  || "—";
    const notes    = answers[nid] || "";
    return `  ${label}\n  Priority: ${priority}${notes ? `\n  Notes: ${notes}` : ""}`;
  }).join("\n\n");

  return `MB3 DESIGN × MAUGHAN / MYOSITE DIAGNOSTIC
STRATEGIC ALIGNMENT — SCOPE INTAKE
Date: ${date} | Session: ${sessionId}
${"═".repeat(60)}

01 — OUTCOMES & PRIORITIES
─────────────────────────
Top priorities (6–12 months):
${answers["q_outcomes_12mo"] || "—"}

Role of the cataract patent:
${answers["q_patent_role"] || "—"}

EBV / Long COVID research status:
${answers["q_ebv_status"] || "—"}

Hard blockers:
${answers["q_blockers"] || "—"}


02 — TIMELINE & MILESTONES
──────────────────────────
Hard deadlines / milestone pressure:
${answers["q_deadlines"] || "—"}

Real progress in 90 days:
${answers["q_first_milestone"] || "—"}

12-month success picture:
${answers["q_horizon"] || "—"}


03 — WORK TRACKS
─────────────────
${tracks}


04 — SCOPE & BUDGET
────────────────────
Preferred engagement model:
${answers["q_budget_model"] || "—"}

Hours per week estimate:
${answers["q_hours_week"] || "—"}

Work rhythm:
${answers["q_work_rhythm"] || "—"}

Additional notes:
${answers["q_budget_notes"] || "—"}


${"═".repeat(60)}
Generated by MB3 Design Client Collaboration Platform
`;
}
