export const SECTIONS = [
  {
    id: "outcomes",
    label: "01 — Outcomes",
    title: "What do you want to achieve?",
    color: "#E8600A",
    questions: [
      {
        id: "q_outcomes_12mo",
        label: "Top priorities in the next 6–12 months",
        hint: "Commercial, research, validation, publication — what matters most right now?",
        type: "textarea",
      },
      {
        id: "q_patent_role",
        label: "Role of the cataract patent",
        hint: "Primary commercial vehicle, licensing opportunity, academic publication path, or foundation to build from?",
        type: "textarea",
      },
      {
        id: "q_ebv_status",
        label: "EBV / Long COVID research — current status",
        hint: "Where are you in the arc: hypothesis, data collection, analysis, writing? What's the goal?",
        type: "textarea",
      },
      {
        id: "q_blockers",
        label: "Hard blockers right now",
        hint: "Time, team, validation data, institutional access, funding — what's actually in the way?",
        type: "textarea",
      },
    ],
  },
  {
    id: "timeline",
    label: "02 — Timeline",
    title: "When do things need to happen?",
    color: "#0D9488",
    questions: [
      {
        id: "q_deadlines",
        label: "Hard deadlines or milestone pressure",
        hint: "Grants, partnerships, publications, collaborations — anything with a date attached?",
        type: "textarea",
      },
      {
        id: "q_first_milestone",
        label: "What would 'real progress' look like in 90 days?",
        hint: "Concrete — a prototype built, a paper submitted, a workflow running, a partner engaged.",
        type: "textarea",
      },
      {
        id: "q_horizon",
        label: "12-month success — what does it look like?",
        hint: "Paint the picture. Where do you want to be a year from now across all active tracks?",
        type: "textarea",
      },
    ],
  },
  {
    id: "tracks",
    label: "03 — Work Tracks",
    title: "Where should we focus?",
    color: "#7C3AED",
    questions: [
      {
        id: "q_track_cataract",
        label: "Cataract patent → prototype",
        hint: "Live / Active / Background / Pause — and why?",
        type: "priority",
        options: ["1 — Lead priority", "2 — Active", "3 — Background", "Pause for now"],
        notes_id: "q_track_cataract_notes",
        notes_hint: "What specifically do you need here?",
      },
      {
        id: "q_track_domains",
        label: "Tangential domain applications",
        hint: "Applying the psychophysical method beyond cataracts — macular, diabetic, etc.",
        type: "priority",
        options: ["1 — Lead priority", "2 — Active", "3 — Background", "Pause for now"],
        notes_id: "q_track_domains_notes",
        notes_hint: "Which domains feel most credible to you scientifically?",
      },
      {
        id: "q_track_ebv",
        label: "EBV / Long COVID research support",
        hint: "Literature synthesis, research pipeline, org infrastructure, grant writing.",
        type: "priority",
        options: ["1 — Lead priority", "2 — Active", "3 — Background", "Pause for now"],
        notes_id: "q_track_ebv_notes",
        notes_hint: "Where's the biggest bottleneck — literature, synthesis, writing, collaboration?",
      },
      {
        id: "q_track_ai",
        label: "AI agentic workflows & automation",
        hint: "Automating repetitive research tasks, building agentic team infrastructure.",
        type: "priority",
        options: ["1 — Lead priority", "2 — Active", "3 — Background", "Pause for now"],
        notes_id: "q_track_ai_notes",
        notes_hint: "Where are you losing the most time to repetitive work right now?",
      },
    ],
  },
  {
    id: "budget",
    label: "04 — Scope & Budget",
    title: "How do we structure the work?",
    color: "#D97706",
    questions: [
      {
        id: "q_budget_model",
        label: "How do you think about engaging outside expertise?",
        hint: "By the hour, by outcome, by relationship / retainer — what feels right?",
        type: "radio",
        options: ["Hours per week retainer", "Milestone / outcome-based", "Hybrid — retainer base + milestone bonuses", "Not sure yet"],
      },
      {
        id: "q_hours_week",
        label: "Hours per week — realistic estimate across all active tracks",
        hint: "Don't anchor to a number — just your gut feel. 2 hrs? 5 hrs? 10 hrs? More?",
        type: "radio",
        options: ["2–4 hrs / week", "5–8 hrs / week", "10–15 hrs / week", "15–20+ hrs / week"],
      },
      {
        id: "q_work_rhythm",
        label: "Work rhythm",
        hint: "Consistent week-over-week, or spikes around milestones and deliverables?",
        type: "radio",
        options: ["Steady — same effort each week", "Burst-heavy — spikes around milestones", "Mixed — steady base with occasional bursts", "Depends on the track"],
      },
      {
        id: "q_budget_notes",
        label: "Anything else on budget or structure?",
        hint: "Constraints, preferences, things that have worked or not worked with other engagements.",
        type: "textarea",
      },
    ],
  },
];
